### ISSUE TITLE
How to install custom watchfaces on AsteroidOs?

### ISSUE THREAD

**Issue by DiggroDI01** [AsteroidOS/unofficial-watchfaces#18]
Can anyone be kind to give step by step instruction to install custom watchfaces on AsteroidOs for windows user.

**Comment by jrtberlin** [comment]
Hi, the `deploy.sh` script is not a Windows shell script.

### Explanation
`.sh` is historically referring to the [Bourne shell's](https://en.wikipedia.org/wiki/Bourne_shell) executable name `sh`. 
On most UNIX(-like) systems, file extensions don't matter and are more or less for humans to know what a file is all about. So in this case it is a UNIX shell script.
The first line in a shell script, the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)), indicates which shell should execute the content of the script. In our case bash (`#!/bin/bash`). Windows does not ship with `sh` and/or `bash`. There are solutions like [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), but it seems like [USB is still a no-go](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations).

### How to install custom watchfaces without the script
If you have `scp` on your system you can try following [our documentation](https://asteroidos.org/wiki/package-installation/#watchfaceinstallation).

If you don't have `scp`, you can try using `adb` instead.
The general syntax is: `adb push file.extension /path/on/watch/file.extension`
1. switch to "ADB Mode" in the USB settings.
2. `adb push watchface-name.qml /usr/share/asteroid-launcher/watchfaces/`
3. If the watchface needs fonts you can push them to: `/usr/share/fonts/`
4. If the watchface needs other assets just push them to `/usr/share/asteroid-launcher/watchfaces/`

**Comment by DiggroDI01** [comment]
Thank you so much ❤️ .now I understand.thanks again.
