### ISSUE TITLE
Digital watchfaces are not honoring 12hr/24hr format selection in Settings>Units

### ISSUE THREAD

**Issue by basnappl** [AsteroidOS/unofficial-watchfaces#19]
Hi, most (all?) of the digital watchfaces seem to ignore the 12hr vs. 24hr setting (called "Use 12hr format) in the AsteroidOS settings under "Units".  They do show AM/PM but always show time in 24hr format regardless of this setting.

**Comment by eLtMosen** [comment]
Since the July 11th nightlies all watchface respect the 12/24H settings.
Thanks for spotting and reporting this!
