### ISSUE TITLE
analog-scientific hour hand does not always update

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/unofficial-watchfaces#48]
@beroset reported on matrix

> When I use the analog-scientific (either the original or the v2 in progress, and the watch is dimmed for some time, the hour hand does not seem to update.

**Comment by beroset** [comment]
OK, here are some results from the overnight test.  The following watchfaces have that same problem:

1. analog-asteroid-logo
2. analog-railway
3. analog-scientific
4. analog-scientific-v2
5. analog-tactical
6. sporty-round
7. sporty-round-v2

These were checked and seem OK:
analog-aviator, analog-classy-roman, analog-halloween, analog-modern-steel, analog-neon-diver, analog-nort, analog-precision, analog-red-handed, analog-rings, analog-silly-walks, analog-words, analog-words-80s, decimal-time, motivational-quotes, orbiting-asteroids
