### ISSUE TITLE
provide a simple means of cloning a watchface

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/unofficial-watchfaces#50]
In discussion on matrix, @eLtMosen suggested the idea of being able to easily clone a watchface as a starting point for creating a new variant.  Ideally this should be done in a shell script without adding too many new requirements to be able to run, as contrasted with, for example, writing such a utility in Perl or Python.

**Comment by MagneFire** [comment]
I've created a similar script for starting new ports: https://gist.github.com/MagneFire/968929530901361543fa5bf15ca4567c
All it does is create a new layer and replace all occurrences in files and rename files and folders.
This might be helpful here too?

**Comment by beroset** [comment]
The script I've mostly written is very similar.  One difference is that it uses `cp -r` to efficiently copy everything, and then only renames/rewrites files containing the original name.  Almost ready for commit.

**Comment by eLtMosen** [comment]
Your kind pull request more than satisfied what i originally had imagined.
Closing with a big thank you @beroset
