### ISSUE TITLE
How are watchfaces ported to AsteroidOS? Are Watchmaker watchfaces compatible?

### ISSUE THREAD

**Issue by BalooRJ1** [AsteroidOS/unofficial-watchfaces#68]
Hello,

Forgive me for this question as I am not too familiar with the world of wearables, but this project looks like a fantastic one as I am an enthusiastic supporter of FOSS projects.

My main question is how are watchfaces designed and ported to AsteroidOS? Can some of the watchfaces from the Watchmaker app (such as this one, for example https://getwatchmaker.com/watchface/timex-expedition-model-t43371) be ported to AsteroidOS?

Thank you.

**Comment by eLtMosen** [comment]
Hey @BalooRJ1 
Watchfaces on AOS are qml applications. Writing them is not too complicated if you have prior knowledge of any programming language. We have a watchface creation guide for some details:
https://asteroidos.org/wiki/watchfaces-creation/

Porting watchfaces could be done by using a AOS watchface that uses rotated SVG or PNG images. Then swap in the images  from the to be paorted watchface.
There is no automated process for to do that at this time however.
If you have detailed question on a watchface you want to port, just ask here or join the matrix chat where questions might get quicker feedback!

**Comment by BalooRJ1** [comment]
@eLtMosen Thank you very much for the quick reply. I have a lot of questions about AsteroidOS so I think I'll join the Matrix and ask them there!

**Comment by eLtMosen** [comment]
Closing this, feel free to reopen or make a new issue with specific questions!
